### PR TITLE
[Bug Fix] Spam Alerts + Code Clean % Change

### LINKED ISSUE #23: [Discussion] [Improvement] Reducing spam without missing out on critical information
Quite a bit has been done previously in reducing unnecessary spam in 
https://github.com/brianleect/binance-pump-alerts/issues/6
https://github.com/brianleect/binance-pump-alerts/issues/20

which have been adequately addressed as the spam was mostly information we see as unnecessary.

However, in this new issue regarding spam, it is actually clear that we are getting what we want which is a clear signal for a pump with '1s' interval getting triggered multiple times as shown below.

image

image

If anyone managed to managed to open a margin short position ~55, close to 50-60% profits would have been achieved selling at the current dumped prices. So it is clear that the alert in this scenario is valid.

However, while the objective of alerting us to a pump has been achieved, close to 20 alert notifications were sent within a 5 minute period which does seem a little unnecessary.

**Possible Solutions**
1. Integrate back MIN_ALERT_INTERVAL (Takes the longer period between actual interval vs MIN_ALERT_INTERVAL)
1a. Cons: Might potentially miss out on critical pump information

2. Prevent normal pump price volatility from triggering alerts
Can be achieved by comparison of price from previous trigger. And require % deviation form previous trigger to be considered valid?

I'm open to suggestions as well on possible alternatives so feel free to comment below!

### PR DESCRIPTION
**Pull request by brianleect**
Fixed Spam Alerts by creation of 'lt_price' key value pair which stores **last triggered alert price**. 

To trigger alert 2 conditions now have to be met
1. Change >= Outlier Param
2. Change relative to last triggered alert price >= Outlier Param as well

(We will ignore the other factors such as MIN_ALERT_INTERVAL as they are not relevant to the problem at hand)

---------------
Code Cleaning % Change in price

Previously there was a small portion of repeated code, combined them to shorten code and for overall code quality.

### CODE REVIEW

**Comment by brianleect** [comment]
Will merge the pull and start running it on the ec2 to test results.

**Comment by Juanjacinto123** [comment]
> Fixed Spam Alerts by creation of 'lt_price' key value pair which stores **last triggered alert price**.
> 
> To trigger alert 2 conditions now have to be met
> 
> 1. Change >= Outlier Param
> 2. Change relative to last triggered alert price >= Outlier Param as well
> 
> (We will ignore the other factors such as MIN_ALERT_INTERVAL as they are not relevant to the problem at hand)
> 
> Code Cleaning % Change in price
> 
> Previously there was a small portion of repeated code, combined them to shorten code and for overall code quality.

I think it is an excellent idea to save the last price change and compare it. However I would still like to use the MIN_ALERT_INTERVAL option, is it still possible?

**Comment by brianleect** [comment]
> > Fixed Spam Alerts by creation of 'lt_price' key value pair which stores **last triggered alert price**.
> > To trigger alert 2 conditions now have to be met
> > 
> > 1. Change >= Outlier Param
> > 2. Change relative to last triggered alert price >= Outlier Param as well
> > 
> > (We will ignore the other factors such as MIN_ALERT_INTERVAL as they are not relevant to the problem at hand)
> > Code Cleaning % Change in price
> > Previously there was a small portion of repeated code, combined them to shorten code and for overall code quality.
> 
> I think it is an excellent idea to save the last price change and compare it. However I would still like to use the MIN_ALERT_INTERVAL option, is it still possible?

This PR should not have impacted MIN_ALERT_INTERVAL. It should function the same as before. We just have an additional check now for the price compared to last trigger before we allow an alert to be sent.

**Comment by Juanjacinto123** [comment]
> > > Fixed Spam Alerts by creation of 'lt_price' key value pair which stores **last triggered alert price**.
> > > To trigger alert 2 conditions now have to be met
> > > 
> > > 1. Change >= Outlier Param
> > > 2. Change relative to last triggered alert price >= Outlier Param as well
> > > 
> > > (We will ignore the other factors such as MIN_ALERT_INTERVAL as they are not relevant to the problem at hand)
> > > Code Cleaning % Change in price
> > > Previously there was a small portion of repeated code, combined them to shorten code and for overall code quality.
> > 
> > 
> > I think it is an excellent idea to save the last price change and compare it. However I would still like to use the MIN_ALERT_INTERVAL option, is it still possible?
> 
> This PR should not have impacted MIN_ALERT_INTERVAL. It should function the same as before. We just have an additional check now for the price compared to last trigger before we allow an alert to be sent.
> 
> Or are you asking if we can disable this additional check?



> > > Fixed Spam Alerts by creation of 'lt_price' key value pair which stores **last triggered alert price**.
> > > To trigger alert 2 conditions now have to be met
> > > 
> > > 1. Change >= Outlier Param
> > > 2. Change relative to last triggered alert price >= Outlier Param as well
> > > 
> > > (We will ignore the other factors such as MIN_ALERT_INTERVAL as they are not relevant to the problem at hand)
> > > Code Cleaning % Change in price
> > > Previously there was a small portion of repeated code, combined them to shorten code and for overall code quality.
> > 
> > 
> > I think it is an excellent idea to save the last price change and compare it. However I would still like to use the MIN_ALERT_INTERVAL option, is it still possible?
> 
> This PR should not have impacted MIN_ALERT_INTERVAL. It should function the same as before. We just have an additional check now for the price compared to last trigger before we allow an alert to be sent.
> 
> Or are you asking if we can disable this additional check?

What I understand is that the new alert will continue to be sent as long as the change is greater than or equal to what was previously notified. Am I correct?

For example:

intervals = [''5m', '15m']
outlier_param = {'5m':0.02,'15m':0.04,'} 

First notification: 
"PUMP: TCTUSDT / Change: 2.5% / Price: 0.023277 / Interval: 5m"

Muted notification: 
"PUMP: TCTUSDT / Change: 2.3% / Price: 0.023277 / Interval: 5m"

Second notification: 
"PUMP: TCTUSDT / Change: 2.6% / Price: 0.023277 / Interval: 5m"

**Comment by brianleect** [comment]
> What I understand is that the new alert will continue to be sent as long as the change is greater than or equal to what was previously notified. Am I correct?
> 
> For example:
> 
> intervals = [''5m', '15m']
> outlier_param = {'5m':0.02,'15m':0.04,'} 
> 
> First notification: 
> "PUMP: TCTUSDT / Change: 2.5% / Price: 0.023277 / Interval: 5m"
> 
> Muted notification: 
> "PUMP: TCTUSDT / Change: 2.3% / Price: 0.023277 / Interval: 5m"
> 
> Second notification: 
> "PUMP: TCTUSDT / Change: 2.6% / Price: 0.023277 / Interval: 5m"
> 

In this case the 2nd & 3rd notification will both not be triggered as the second condition trigger condition is not satisfied which is price must have a movement of larger than that of previous triggered price alert

Outlier_param * 0.023277

The intention was that there is little value in price alerts triggered which have little to no deviation in price.

**Comment by Juanjacinto123** [comment]
> > What I understand is that the new alert will continue to be sent as long as the change is greater than or equal to what was previously notified. Am I correct?
> > For example:
> > intervals = [''5m', '15m']
> > outlier_param = {'5m':0.02,'15m':0.04,'}
> > First notification:
> > "PUMP: TCTUSDT / Change: 2.5% / Price: 0.023277 / Interval: 5m"
> > Muted notification:
> > "PUMP: TCTUSDT / Change: 2.3% / Price: 0.023277 / Interval: 5m"
> > Second notification:
> > "PUMP: TCTUSDT / Change: 2.6% / Price: 0.023277 / Interval: 5m"
> 
> In this case the 2nd & 3rd notification will both not be triggered as the second condition trigger condition is not satisfied which is price must have a movement of larger than that of previous triggered price alert
> 
> Outlier_param * 0.023277
> 
> The intention was that there is little value in price alerts triggered which have little to no deviation in price.


I understand, that is to say that the percentages are accumulated.

I think that the most optimal for the second trigger condition would be that the next value is simply greater than the previous one.

As in the previous example:

intervals = [''5m']
outlier_param = {'5m':0.02}

First notification:
"PUMP: TCTUSDT / Change: 2.5% / Price: 0.023277 / Interval: 5m"

Second (Muted) notification:
"PUMP: TCTUSDT / Change: 2.3% / Price: 0.023277 / Interval: 5m"

Third notification:
"PUMP: TCTUSDT / Change: 2.6% / Price: 0.023277 / Interval: 5m" 

The way you propose it is optimal for small percentages, but when handling slightly larger percentages, say greater than 4 or 5%, many alerts would be lost.

**Comment by brianleect** [comment]
> > > What I understand is that the new alert will continue to be sent as long as the change is greater than or equal to what was previously notified. Am I correct?
> > > For example:
> > > intervals = [''5m', '15m']
> > > outlier_param = {'5m':0.02,'15m':0.04,'}
> > > First notification:
> > > "PUMP: TCTUSDT / Change: 2.5% / Price: 0.023277 / Interval: 5m"
> > > Muted notification:
> > > "PUMP: TCTUSDT / Change: 2.3% / Price: 0.023277 / Interval: 5m"
> > > Second notification:
> > > "PUMP: TCTUSDT / Change: 2.6% / Price: 0.023277 / Interval: 5m"
> > 
> > 
> > In this case the 2nd & 3rd notification will both not be triggered as the second condition trigger condition is not satisfied which is price must have a movement of larger than that of previous triggered price alert
> > Outlier_param * 0.023277
> > The intention was that there is little value in price alerts triggered which have little to no deviation in price.
> 
> I understand, that is to say that the percentages are accumulated.
> 
> I think that the most optimal for the second trigger condition would be that the next value is simply greater than the previous one.
> 
> As in the previous example:
> 
> intervals = [''5m']
> outlier_param = {'5m':0.02}
> 
> First notification:
> "PUMP: TCTUSDT / Change: 2.5% / Price: 0.023277 / Interval: 5m"
> 
> Second (Muted) notification:
> "PUMP: TCTUSDT / Change: 2.3% / Price: 0.023277 / Interval: 5m"
> 
> Third notification:
> "PUMP: TCTUSDT / Change: 2.6% / Price: 0.023277 / Interval: 5m"
> 
> The way you propose it is optimal for small percentages, but when handling slightly larger percentages, say greater than 4 or 5%, many alerts would be lost.

I think I get your point on possibly filtering of changes with larger % being filtered off. I do suppose it is a trade-off atm of spam  vs potential info.

I'll look into it and see if we can find a solution to this problem. We could possibly overwrite the cooldown and force a trigger if we see a % change relative to previous trigger being met. 

This should solve the problem without introducing unnecessary noise.

**Comment by Farshidtbn** [comment]
I have a important question 
Please please reply me ♥️🙏

**Comment by Farshidtbn** [comment]
Reply to me whenever you see my message, please I messaged you on every network I had

**Pull request merged**
